name: 'Publish Unit Test Results'
author: 'EnricoMi'
description: 'A GitHub Action that publishes unit test results on GitHub'
inputs:
  github_token:
    description: 'GitHub API Access Token'
    required: true
  check_name:
    description: 'Name of the created check run'
    required: false
    default: 'Unit Test Results'
  report_individual_runs:
    description: 'Individual runs of the same test may see different failures. Reports all individual failures when set "true" or the first only otherwise'
    required: false
  files:
    description: 'File pattern of test result files'
    required: true
  log_level:
    description: 'Action logging level'
    required: false
    default: 'INFO'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'green'
