name: CI

on: [push]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: PyTest
      run: |
        cd test
        python -m pytest --junit-xml ../test-results/pytest.xml

    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: test-results/*.xml

    - name: Unit Test Report
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@master
      with:
        check_name: Unit Test Report
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: "test-results/*.xml"
        log_level: DEBUG
